version: '2'
services:
  nginx:
    image: "nginx:alpine"
    volumes:
      - ./nginx-site.conf:/etc/nginx/nginx.conf
    links:
      - app
    ports:
      - "80:80"
  app:
    build: .
    links:
      - db
  db:
    image: "postgres:alpine"
    environment:
      PGDATA: /data
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/data
      - ./create-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  db:
